

export interface Cadrc170SaidasComEntradasModel {

    entId?: number,
    entCoditem?: String,
    entCfop?: number,
    entBcicms?: number,
    entAliqIcms?: number,
    entVlIcms?: number,
    entVlBcst?: number,
    entAliqSt?: number,
    entIcmsSt?: number,
    entBcIpi?: number,
    entAliqIpi?: number,
    entVlIpi?: number,
    entCstPis?: String,
    entBcPis?: number,
    entAliqPis?: number,
    entCstCofins?: String,
    entBcCofins?: number,
    entAliqCofins?: number,
    entChvnfe?: String,
    saiId?: number,
    saiCoditem?: String,
    saiCfop?: number,
    saiBcicms?: number,
    saiAliqIcms?: number,
    saiVlIcms?: number,
    saiVlBcst?: number,
    saiAliqSt?: number,
    saiIcmsSt?: number,
    saiBcIpi?: number,
    saiAliqIpi?: number,
    saiVlIpi?: number,
    saiCstPis?: String,
    saiBcPis?: number,
    saiAliqPis?: number,
    saiCstCofins?: String,
    saiBcCofins?: number,
    saiAliqCofins?: number,
    saiChvnfe?: String,
    saiCabFrete?: number,
    saiCabSeg?: number,
    saiCabOutDa?: number,
    saiCabBcicms?: number,
    saiCabVlicms?: number,
    saiCabBcicmsst?: number,
    saiCabVlicmsst?: number,
    saiCabVlipi?: number,
    saiCabVlpis?: number,
    saiCabVlcofins?: number,
    saiCabVlpisSt?: number,
    saiCabVlcofinsSt?: number,
    chassis?: String,
    saiDescrItem?: String,
    saiDtDoc?: Date,
    saiVlDoc?: number,
    saiNomeCliente?: String,    
    entDescrItem?: String,
    entDtDoc?: Date,
    entVlDoc?: number,
    entNomeFor?: String
}

